name: Docker Image


on:
  push:
    branches:
      - master
  release:
    types:
      - published


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Clear Space
#        run: |
#          rm -rf /usr/share/dotnet
#          rm -rf /opt/ghc
#          rm -rf "/usr/local/share/boost"
#          rm -rf "$AGENT_TOOLSDIRECTORY"
#
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push runpod docker
        uses: docker/build-push-action@v4
        with:
#          build-args: |
#            MODEL_URL=${{ matrix.model_url }}
#            MODEL_TAG=${{ matrix.model_tag }}
          file: deploy/runpod/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}/test:latest
